### ISSUE TITLE
Monkey patching of root methods

### ISSUE THREAD

**Issue by matthew-dean** [solkimicreb/react-easy-state#67] opened 2018-11-19 22:40 UTC
Is the monkey-patching of root methods (setTimeout, requestAnimationFrame, Promise) necessary (if I'm reading the source files correctly)? I'm worried about the performance impact of these global modifications. Why does this state library tweak so many global objects?

**Comment by solkimicreb** [comment] 2018-11-20 08:55
It's a temporary batching mechanism until concurrent React and its scheduler are ready. After that I will switch to React's own scheduler.

Scheduling is necessary because mutatable data stores do not have the inherent batching of setState (where you send the whole data change in on object). For example, splicing an array mutates it multiple times in quick succession which could cause unnecessary renders. The current temporary sync batching scheduler makes sure to render only once.

I wanted to use an async scheduler first, but React's current batching is sync so it would be very alien for most people. After React's new priority based async scheduler is out and stable I will remove that code in favour of it.

**Comment by solkimicreb** [comment] 2018-11-23 05:17
I am closing this, feel free to reopen if needed.

**Comment by matthew-dean** [comment] 2018-11-23 18:50
Unfortunately, this breaks all of our Enzyme tests because of the batching. I may try re-writing something like react-easy-state based on the underlying observer-util. :/

**Comment by matthew-dean** [comment] 2018-11-23 18:52
As far as this:
```
Scheduling is necessary because mutatable data stores do not have the inherent batching of setState (where you send the whole data change in on object). For example, splicing an array mutates it multiple times in quick succession which could cause unnecessary renders. The current temporary sync batching scheduler makes sure to render only once.
```
The preferable architecture would be to force dataset updates to be batched (force a developer to batch their mutations), rather than monkey patching in this way.

**Comment by solkimicreb** [comment] 2018-11-23 19:00
Ouch, that shouldn't happen. I will try to include a fix in the next version (coming early next week)

I had all my tests written in enzyme until very recently without any issues. Can you share part of your code and the errors/stack traces to resolve this?

**Comment by solkimicreb** [comment] 2018-11-23 19:05
For now I would like to continue with auto batching and fix all issues. I am pretty sure it is doable (angular has a lot more patching and it works perfectly).

As a last resort I could add an opt out api or if you want to fork the repo I can help you to remove batching completely.

In the end I hope to get rid of this issue with a future React version.

**Comment by matthew-dean** [comment] 2018-11-23 19:35
All my tests are passing now. Sorry about that!

**Comment by matthew-dean** [comment] 2018-11-29 07:43
I may have spoken too soon. Monkey patching these scheduling/timing methods app-wide and batching all calls to these globals from ANYWHERE seems to have unintended side-effects. I'll have to investigate further, but it seems in cases like controller input, which is constantly polled via `requestAnimationFrame`, and then debounced via `setTimeout`, there are cases where adding this dependency might have caused regressions where controller input is not properly debounced. As in, with Lodash's debounce, it's supposed to not fire a function within a span of time. But after I added this module as a dependency, now it seems like `debounce` is handling unreliably. I have to suspect that it has something to do with batching here, although I can't yet say for sure.

Can't you patch just around React's `scheduler` module? (https://www.npmjs.com/package/scheduler). As in create a module to alias in webpack?

I would think altering behavior globally of these methods is just prone to lots of unintended side-effects.

**Comment by solkimicreb** [comment] 2018-11-29 19:41
When scheduler and concurrent react is ready we wont need monkey patching anymore. Unfortunately the scheduler package is not even an alpha yet, so I have to wait with removing the patched batching. Which version of easy state are you using? There is an important batching fix in the latest patch.

**Comment by matthew-dean** [comment] 2018-11-29 23:10
@solkimicreb 6.0.5. What was the issue that was patched, and could it affect what I'm describing? It's a really hard problem to track down so I'm not even sure if this is the issue; it's more like the bug re-appeared shortly (and only happens sporadically, hard to repro) after adding `react-easy-state` so it's more like a strong suspect, but I really don't know.

**Comment by solkimicreb** [comment] 2018-11-30 11:13
Yep, it could be the cause Could you try upgrading to 6.0.6?  (it fixed a broken return value from patched methods).

Thanks!

**Comment by solkimicreb** [comment] 2019-01-31 19:48
Can I close this?

**Closed** 2019-02-05 18:47 UTC
