### ISSUE TITLE
How to use with React Hooks

### ISSUE THREAD

**Issue by cayasso** [solkimicreb/react-easy-state#59] opened 2018-10-28 05:01 UTC
What are your vision of using `react-easy-state` with the new and fresh React Hooks?
https://reactjs.org/docs/hooks-intro.html

**Comment by solkimicreb** [comment] 2018-10-28 05:30
No idea yet. I am on a holiday with very limited internet. I will catch up with React news in a week when I get back. (I guess there is a lot of news)

**Comment by cayasso** [comment] 2018-10-28 05:35
Yup lot of news! This is not a question only for this library but also for other state libraries like Mobx so I think by when your are back there might be some addition research from others on how to use, I will try to research my self.
So in the mean time enjoy your vacations ;-)

**Comment by cayasso** [comment] 2018-10-28 07:08
So this is what I have come up with so far:

```js
import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";
import { store, view } from "react-easy-state";
import { observe, unobserve } from "@nx-js/observer-util";

const useEasyState = store => {
  const [state, setState] = useState(store);

  const handleStateChange = () => {
    console.log(state);
    setState({ ...state });
  };

  useEffect(
    () => {
      const fn = observe(handleStateChange);
      return () => unobserve(fn);
    },
    [store]
  );

  return state;
};

const counter = store({
  num: 0,
  increment: () => {
    return counter.num++;
  }
});

const Counter = () => {
  console.log("RENDERING");
  const { increment, num } = useEasyState(counter);
  return <button onClick={increment}>{num}</button>;
};

function App() {
  return (
    <div className="App">
      <Counter />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

The `useEasyState` does all the trick delegating the store value to the hook state it self and thats it, there might be some minor things that I am not considering but its a starting point. With this you can import the hook like this.

```js
import { useEasyState } from 'react-easy-state'
```

Let me know what you think when you are back.

**Comment by cayasso** [comment] 2018-10-28 07:12
Here is the working example:
https://codesandbox.io/s/n49v8llw70

**Comment by solkimicreb** [comment] 2018-11-06 11:54
Hi All! I am back 🙂 

Thanks for all the demos so far, I will catch up with them in the afternoon.

**Comment by solkimicreb** [comment] 2018-11-07 12:36
Thanks for the effort @cayasso and @Penspinner. Here is my feedback/thoughts:

- I think migrating internally to react-hooks without an external API change has no big benefit. The current React state will continue to be supported and the current perf is pretty good.

- We could simplify the API down to single function much like @cayasso did. With hooks we wouldn't even need `store`, just the `useStore` function. (Use store can wrap the passed object with a reactive store, since store wrapping is idempotent).

Something like:

```jsx
import React from "react";
import ReactDOM from "react-dom";
import { useStore } from "react-easy-state";

const counter = {
  num: 0,
  inc: () => {
    return counter.num++;
  }
};

const Counter = () => {
  const { inc, num } = useStore(counter);
  return <button onClick={inc}>{num}</button>;
};

const rootElement = document.getElementById("root");
ReactDOM.render(<Counter />, rootElement);
```

There are two questions to consider:

1. How to add this? Should we keep the current 2 function API and add this new function as a different way of usage?

2. How to support local state?

Let me know what you think.

**Comment by ivan-kleshnin** [comment] 2018-11-07 12:43
My 5 cents.

> How to add this? Should we keep the current 2 function API and add this new function as a different way of usage?

I'm fine with `view` + `useStore` as you proposed. Personally, I don't see a value in state methods (they are not composable and spray logic into different places) but that's another question.

> How to support local state?

I would say state is "local" or "global" depending on the file it's located in... and that's all. 
No extra technical differences are required.

**Comment by Penspinner** [comment] 2018-11-08 00:32
> I think migrating internally to react-hooks without an external API change has no big benefit. The current React state will continue to be supported and the current perf is pretty good.

Yes. I know. Just trying to see if the implementation was correct or if it would be cool to try it out.

One thing I'm not sure about is would `useStore(counter)` create a global store? Would another component that `useStore(counter)` be re-rendered if the other component mutates `counter` properties?

```jsx
import React from "react";
import ReactDOM from "react-dom";
import { useStore } from "react-easy-state";

const counter = {
  num: 0,
  inc: () => {
    return counter.num++;
  }
};

const Counter1 = () => {
  const { inc, num } = useStore(counter);
  return <button onClick={inc}>{num}</button>;
};

const Counter2 = () => {
  const { inc, num } = useStore(counter);
  return <button onClick={inc}>{num}</button>;
};

const App = () => (
  <>
    <Counter1 />
    <Counter2 />
  </>
);

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by cayasso** [comment] 2018-11-08 06:18
Welcome back @solkimicreb hope you enjoyed your vacations!

- I pretty much agree with all that @ivan-kleshnin mentioned. `view` + `useStore` and that `local` vs `global` doesn't really matter in this case.

- @solkimicreb in your example I don't think it is possible for `useStore` to wrap the object with a reactive store, because (and correct me if I am wrong) the object need a reference to the reactive object for example:

```js
const counter = {
  num: 0,
  inc: () => {

    // won't work, it need a reference to "counterStore"
    return counter.num++;

    // will work because its a reference to reactive counterStore
    return counterStore.numm++;
  }
}

const counterStore = store(counter)
```

**Comment by ivan-kleshnin** [comment] 2018-11-08 09:03
@NaNdreas the update is not released yet. Current `easy-state` will indeed cause that error.

> I'm really just worried about the API changing too much (a lot of refactoring)

To my understanding, everything is 100% backward compatible. It's only if you move to hooks in your code base – you'll need to apply this new API.

**Comment by solkimicreb** [comment] 2018-11-09 15:52
I did some research and everything I wrote so far was more or less incorrect, sorry about that. Now I have a [tiny working demo](https://codesandbox.io/s/p2wnvw1wp7) to back up the ideas. Big thanks @Penspinner for your demo! My one is a slightly modified version of yours.

I hoped to shrink the current API to a single hook, but it turned out that we have to keep both the `store` (as @cayasso pointed out) and the `view` function. The good news is that we can continue to support all use cases with the current API at least.

This is the proposed API for the new use cases.

- The new version will work with pre-react-16.7 class and function components. (No breaking changes)
- It will work together with hooks and support local state in  React 16.7+ function components.

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { view, store } from 'react-easy-state';

// this is a global store which is shared between component instances
const globalStore = store({ show: true })

const toggleShow = () => (globalStore.show = !globalStore.show)

// using store inside a function component creates a local store that is not shared between component instances
const Counter = view(() => {
  const localStore = store({ num: 12 })
  const inc = () => localStore.num++

  return <button onClick={inc}>{localStore.num}</button>
});

const App = view(() => (
  <div>
    {globalStore.show && <Counter />}
    <button onClick={toggleShow}>Toggle Counter</button>
  </div>
))

ReactDOM.render(<App />, document.getElementById('root'));
```

You can find the codesandbox demo with the initial implementation [here](https://codesandbox.io/s/p2wnvw1wp7).

Let me know what you think.

**Comment by cayasso** [comment] 2018-11-09 17:35
It looks great to me, I like the fact that we continue using the same API, there is one change only, I noticed that in `easyState.js` you have this line `scheduler: setState,`, this line like that will cause the following error when using regular react hooks in a function with `view(...)`:
```
TypeError: Cannot read property '0' of undefined
```
You can reproduce the error here https://codesandbox.io/s/l5nkkqqp0l notice what happen when you increment.

The solution is to use `scheduler: () => setState(),` as in @Penspinner initial code.

**Comment by Penspinner** [comment] 2018-11-10 17:17
@solkimicreb 

Just tried your example. Looks fine except for a few things.

- When pressing the Toggle Counter button, `App` gets logged to the console twice. Not sure why. Is it supposed to do that?
- Also one thing I noticed about the `store` function is that the React team emphasized that hooks should be in the top level at all times to function correctly. So `useMemo` shouldn't be in an `if` statement. It seems to work fine in your example, so Idk. https://reactjs.org/docs/hooks-rules.html

**Comment by solkimicreb** [comment] 2018-11-17 10:44
I hope to have some time over the weekend to implement this.

Thanks for the feedback @Penspinner 

> When pressing the Toggle Counter button, "App" is logged to the console twice. Not sure why. Is it supposed to do that?

This is a bug, I will look into it.

> I noticed the store function is using useMemo within an if statement. The React team emphasized that hooks should be at the top level of a React function at all times to ensure things work as expected. It seems to work fine in your example, but not sure if it would function correctly all the times. https://reactjs.org/docs/hooks-rules.html

This won't be an issue. Every hook must be called in the exact same order on every render. (This is a lower level equivalent oh the 'hook rules'). My `if` block is doing exactly this, it calls `useMemo` when `store` is invoked from inside a render and does not call it otherwise. Without the `if` block we would actually break react because of the hooks called outside from renders. I will make sure to comment the final code about this.

**Comment by solkimicreb** [comment] 2018-11-22 20:44
Hooks update is ready, you can try the beta release with `npm i react-easy-state@beta`. The new code and readme is on [this branch](https://github.com/solkimicreb/react-easy-state/tree/hooks). Everything is as discussed in the final comments.

Please play with it a bit if you have some time. I don't expect to add any breaking changes, so don't be afraid to try it out. Thanks everyone for the help so far!

**Comment by cayasso** [comment] 2018-11-23 05:46
@solkimicreb thank you for taking the time and implementing this!

**Comment by ivan-kleshnin** [comment] 2018-11-23 11:40
This were somehow caused by `withRouter`:

```
view(withRouter(Layout)) // worked previously
->
withRouter(view(Layout)) // works now
```

No time to investigate, m.b. will help someone.

**Comment by ivan-kleshnin** [comment] 2018-11-23 17:16
> Which version of React Router are you using?

4.3.0 and 4.4.beta

> this is (most probably) not a batching issue

Maybe. The initial reason to think "it's batching" for me was that only `state.loading = ` update was skipped / lost while `state.models =` had effect indeed.

**Comment by solkimicreb** [comment] 2018-11-23 20:36
> Tried with 4.3.0 and 4.4.beta

4.4.beta is using the new context api and I hoped it would eliminate this issue. I will add some React Router interaction tests and look into this before the next release. Thanks for the info again.

**Comment by ivan-kleshnin** [comment] 2018-11-26 10:45
> Are you sure it was working with view(withRouter(Layout)) previously

Yes, absolutely. Otherwise I wouldn't notice this change. I would estimate the probability that it was "something else affecting the impression" as extremely low in this case. Still it could be some weird combination of prop names, etc that made it work when it shouldn't.

**Comment by solkimicreb** [comment] 2018-11-26 10:54
Thanks! Did anyone else run into this issue?

**Comment by ivan-kleshnin** [comment] 2018-12-12 10:13
Coming back to my suspended `hooks` branch  ;) I see that problem with React-Router is bigger than I thought.

Basically, with `6.0.6`, `useEffect` in `view` + functional component triggers:

> Error: Hooks can only be called inside the body of a function component

while this sketch implementation works fine: https://codesandbox.io/s/oq66nmyjpz ...

I've made a repo to demonstrate the bug:
https://github.com/ivan-kleshnin/react-easy-state-bug-demo

See `src/pages/Home.js` files and lines:

```
// export default Home // works fine
export default view(Home) // causes an error
```

**Comment by ivan-kleshnin** [comment] 2018-12-12 10:20
Rechecked once again, and I see no problems with `easy-state@6.1.0-beta.0`, `react@next` and `react-router@next`. All possible sequences of decorators work equally fine in my cases.

**Comment by NaNdreas** [comment] 2019-01-10 10:43
Hi @solkimicreb,

I would love to try this out in my project and let you know how it works, but I need the latest bugfixes on master for my project to work. 

Whenever you have time, would it be possible to do a second beta release with the fixes from master 😄

**Comment by solkimicreb** [comment] 2019-01-10 18:19
Sure, I will try to do it soon. I was pretty busy recently.

**Comment by solkimicreb** [comment] 2019-01-30 18:59
Hi all, the latest beta is out. You can try it with `npm i react-easy-state@beta`. It adds StrictMode compatibility, better batching and a few fixes. Changelog and article will be included with the stable release, which will hopefully happen very soon.

**Comment by solkimicreb** [comment] 2019-01-31 14:46
v6.1.0 (stable) is released with hooks support among others. Short article is [here](https://dev.to/solkimicreb/react-easy-state-v610-hooks-improved-batching-and-strictmode-1bon), changelog is [here](https://github.com/solkimicreb/react-easy-state/releases/tag/v6.1.0).

I am closing the issue now, thanks for the input and help everyone! 🙂

**Closed by solkimicreb** 2019-01-31 14:46 UTC

**Comment by cayasso** [comment] 2019-01-31 14:57
Thank you @solkimicreb!
