### ISSUE TITLE
Error when wrapping class component in view (create-react-app 3.0.0 with easy state)

### ISSUE THREAD

**Issue by Filodoxia** [solkimicreb/react-easy-state#82] opened 2019-04-27 23:44 UTC
Wanted to switch to using create-react-app but ran into an error described in #21. When wrapping a class component in a view I get a "Class constructor App cannot be invoked without 'new'" error (see screenshot). I tried the third solution alternative in said issue (`import { view } from 'react-easy-state/dist/es.es6';`) as well as the standard import since @solkimicreb commented in October that the issue should be resolved but neither work.
I just ran `npx create-react-app myapp`, installed easy state `npm i react-easy-state` and wrapped the App component export in `view`.
Do you guys have any ideas what I might did wrong? Need any more details?

![2019-04-28 01 10 00 localhost 958069742a94](https://user-images.githubusercontent.com/12152527/56856087-ab616680-6953-11e9-86ed-65f431548897.png)

**Comment by solkimicreb** [comment] 2019-04-28 01:13
What version of cra are you using?

**Comment by Filodoxia** [comment] 2019-04-28 21:03
I was doing a clean install, so the latest versions. For easy-state that's 6.1.1 and for CRA 3.0.0. Turns out CRA received a major version update from 2.1.8 to 3.0.0 on Monday (April 22). When I create the app with CRA 2.1.8 it seems to work (will try out more tomorrow, just did the CRA init, installed easy-state and wrapped the App component created by CRA in `view` which fails with version 3). Do I create a new issue for the problem with CRA 3.0.0, or shall I change the title for this issue?

**Comment by solkimicreb** [comment] 2019-04-29 06:28
I think you should stay with cra 2 for now if it is not an issue for you. I
will catch up with cra 3 and update for compatibility soon. (I am on
holiday this week).

**Comment by bleeinc** [comment] 2019-05-06 03:02
Getting the exact same issue. Going to pull down easy state source and give it a look tomorrow.

**Comment by solkimicreb** [comment] 2019-05-10 14:02
Thanks for the help @bleeinc. I was pretty busy recently, but I think I will have some time this weekend.

**Comment by solkimicreb** [comment] 2019-05-21 16:20
I can't really reproduce this. Do you still have this issue? Does it happen right away with a clean cra3 project or did you modify a few things? Did you modify the browserlist config in your package.json?

**Comment by solkimicreb** [comment] 2019-05-21 16:22
Does this happen on both dev and prod mode?

**Comment by solkimicreb** [comment] 2019-05-23 18:58
I can't reproduce this no matter how hard I try. Closing it for now, please doreopen if anyone

**Closed by solkimicreb** 2019-05-23 18:58 UTC
